name: Setup for Python and Pip.

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  echo_python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest  # Install pytest for testing
          pip install git+https://github.com/Aki19-2000/Python-sampleproject.git  # Install from GitHub repo

      - name: Run tests
        run: |
          pytest  # Run tests using pytest

      - name: Create staging directory and copy Python files (if no dist)
        run: |
          mkdir -p staging
          cp *.py staging/  # Copy Python files instead of package artifacts

      - name: Upload package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
